bubblewrap: Autospec creation for update from version 0.5.0 to version 0.6.1
Phaedrus Leeds (1):
      Handle argc == 0 better

Simon McVittie (29):
      Remove obsolete papr CI
      Remove obsolete .travis.yml
      tests: Use preferred spelling for SPDX license identifiers
      Add SPDX-License-Identifier for files that already specify license
      utils: Add warn()
      main: Warn when non-repeatable options are repeated
      die_with_error: Save errno sooner
      bind-mount: Be more const-correct
      bubblewrap: Avoid a -Wjump-misses-init false-positive
      Generalize linked lists of LockFile and SetupOp
      Allow loading more than one seccomp program
      tests: Exercise seccomp filters
      workflows: Update for rename of default branch to main
      Use HEAD to refer to other projects' default branches in documentation
      Add a Meson build system
      meson.build: Remove unnecessary check for sh
      meson: Build tests with equivalent of -I$(top_srcdir) -I$(top_builddir)
      meson: Build the try-syscall helper
      meson: Run the Python test script with Python, not bash
      meson: Make G_TEST_SRCDIR, G_TEST_BUILDDIR match Autotools
      meson: Run test scripts from $srcdir
      tests: Fix compiler warnings for unused arguments
      meson: Actually build and run the tests
      Disable test-specifying-pidns.sh under 'meson dist' while I investigate
      meson: Improve compatibility with Meson 0.49
      Release v0.6.0
      completions: Make zsh completion non-executable
      Add a release checklist
      Prepare v0.6.1

Sönke Hahn (1):
      Fix typo

a1346054 (4):
      bash: Invoke bash using /usr/bin/env
      bash: Fix shellcheck warnings
      Fix spelling
      Remove trailing whitespace